;;; run-tests.el --- Simple test runner for context-navigator -*- lexical-binding: t; -*-

;; Load path (robust: handle batch/interactive where load-file-name or buffer-file-name may be nil)
(let* ((this-file (or load-file-name buffer-file-name default-directory))
       (test-dir (file-name-directory this-file))
       (proj-root (expand-file-name ".." test-dir)))
  (add-to-list 'load-path proj-root)
  (add-to-list 'load-path test-dir))

;; Load modules that tests may need
(require 'context-navigator)
(require 'context-navigator-core)
(require 'context-navigator-events)
(require 'context-navigator-fp)
(require 'context-navigator-model)
(require 'context-navigator-persist)
(require 'context-navigator-gptel-bridge)
(require 'context-navigator-project)
(require 'context-navigator-render)
(require 'context-navigator-icons)
(require 'context-navigator-view)

;; Load tests
(require 'context-navigator-test-helpers)
(require 'context-navigator-events-test)
(require 'context-navigator-fp-test)
(require 'context-navigator-model-test)
(require 'context-navigator-persist-test)
(require 'context-navigator-gptel-bridge-test)
(require 'context-navigator-core-test)
(require 'context-navigator-core-api-test)
(require 'context-navigator-core-push-toggle-test)
(require 'context-navigator-core-project-toggle-test)
(require 'context-navigator-groups-create-switch-test)
(require 'context-navigator-transient-test)
(require 'context-navigator-add-test)
(require 'context-navigator-path-add-test)
(require 'context-navigator-render-indicators-test)
(require 'context-navigator-render-disabled-test)
(require 'context-navigator-view-toggle-enabled-test)
(require 'context-navigator-gptel-apply-fallback-test)
(require 'context-navigator-view-wrap-test)
(require 'context-navigator-core-prune-test)
(require 'context-navigator-render-style-test)
(require 'context-navigator-render-truncate-test)
(require 'context-navigator-transient-tramp-test)
(require 'context-navigator-view-controls-test)
(require 'context-navigator-groups-delete-test)
(require 'context-navigator-mask-tests)
(require 'context-navigator-mask-posix-class-test)
(require 'context-navigator-minibuf-mixed-input-test)
(require 'context-navigator-buffer-mode-test)

(defun context-navigator-run-tests ()
  "Run all ERT tests for context-navigator."
  (interactive)
  (ert t))

(provide 'run-tests)
;;; run-tests.el ends here
