;;; context-navigator-compat-aliases.el --- Compatibility aliases -*- lexical-binding: t; -*-

;; Auto-generated by refactor helper

(eval-when-compile (require 'subr-x))

;; New public names -> old implementations
(when (fboundp 'context-navigator-open-item) (defalias 'context-navigator-visit-item 'context-navigator-open-item))
(when (fboundp 'context-navigator-project-current-root) (defalias 'context-navigator-project-root 'context-navigator-project-current-root))
(when (fboundp 'context-navigator-view--render-items) (defalias 'context-navigator-view-render-items 'context-navigator-view--render-items))
(when (fboundp 'context-navigator-view--render-groups) (defalias 'context-navigator-view-render-groups 'context-navigator-view--render-groups))
(when (fboundp 'context-navigator-view--items-header-toggle-lines) (defalias 'context-navigator-view-items-header-lines 'context-navigator-view--items-header-toggle-lines))
(when (fboundp 'context-navigator-view--items-footer-lines) (defalias 'context-navigator-view-items-footer-lines 'context-navigator-view--items-footer-lines))
(when (fboundp 'context-navigator-view--groups-header-lines) (defalias 'context-navigator-view-groups-header-lines 'context-navigator-view--groups-header-lines))
(when (fboundp 'context-navigator-view--groups-body-lines) (defalias 'context-navigator-view-groups-body-lines 'context-navigator-view--groups-body-lines))
(when (fboundp 'context-navigator-project--interesting-buffer-p/a) (defalias 'context-navigator-project--interesting-buffer-p--advice 'context-navigator-project--interesting-buffer-p/a))
(when (fboundp 'context-navigator-project--current-root/a) (defalias 'context-navigator-project--current-root--advice 'context-navigator-project--current-root/a))

;; Mark old names as obsolete (no aliasing to avoid cycles)
(when (fboundp 'context-navigator-open-item) (make-obsolete 'context-navigator-open-item 'context-navigator-visit-item "1.4.0"))
(when (fboundp 'context-navigator-project-current-root) (make-obsolete 'context-navigator-project-current-root 'context-navigator-project-root "1.4.0"))
(when (fboundp 'context-navigator-view--render-items) (make-obsolete 'context-navigator-view--render-items 'context-navigator-view-render-items "1.4.0"))
(when (fboundp 'context-navigator-view--render-groups) (make-obsolete 'context-navigator-view--render-groups 'context-navigator-view-render-groups "1.4.0"))
(when (fboundp 'context-navigator-view--items-header-toggle-lines) (make-obsolete 'context-navigator-view--items-header-toggle-lines 'context-navigator-view-items-header-lines "1.4.0"))
(when (fboundp 'context-navigator-view--items-footer-lines) (make-obsolete 'context-navigator-view--items-footer-lines 'context-navigator-view-items-footer-lines "1.4.0"))
(when (fboundp 'context-navigator-view--groups-header-lines) (make-obsolete 'context-navigator-view--groups-header-lines 'context-navigator-view-groups-header-lines "1.4.0"))
(when (fboundp 'context-navigator-view--groups-body-lines) (make-obsolete 'context-navigator-view--groups-body-lines 'context-navigator-view-groups-body-lines "1.4.0"))
(when (fboundp 'context-navigator-project--interesting-buffer-p/a) (make-obsolete 'context-navigator-project--interesting-buffer-p/a 'context-navigator-project--interesting-buffer-p--advice "1.4.0"))
(when (fboundp 'context-navigator-project--current-root/a) (make-obsolete 'context-navigator-project--current-root/a 'context-navigator-project--current-root--advice "1.4.0"))

(provide 'context-navigator-compat-aliases)
;;; context-navigator-compat-aliases.el ends here
